const lists = {
  '/list/Z_tblActivities_Standard_Service': [
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Travel from hotel',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:24:37.86Z',
      fModificado: null,
      fborrado: null,
      id: 1,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'After sales assistance',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:24:46.26Z',
      fModificado: null,
      fborrado: null,
      id: 2,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'After sales planned maintenance',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:24:49.343Z',
      fModificado: null,
      fborrado: null,
      id: 3,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Installation group',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:24:53.627Z',
      fModificado: null,
      fborrado: null,
      id: 4,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Installation format',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:24:57.533Z',
      fModificado: null,
      fborrado: null,
      id: 5,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Installation spare parts',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:25:04.207Z',
      fModificado: null,
      fborrado: null,
      id: 6,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: '(Fillable field/other work)',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:25:19.847Z',
      fModificado: null,
      fborrado: null,
      id: 7,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
  ],
  '/list/Z_tblActivities_New_Machine': [
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Travel from/to hotel',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:04.86Z',
      fModificado: null,
      fborrado: null,
      id: 1,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Machine or line installation',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:08.857Z',
      fModificado: null,
      fborrado: null,
      id: 2,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'SAT',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:15.427Z',
      fModificado: null,
      fborrado: null,
      id: 3,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Formats not included in SAT',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:24.12Z',
      fModificado: null,
      fborrado: null,
      id: 4,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Training at customer facility',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:30.92Z',
      fModificado: null,
      fborrado: null,
      id: 5,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Production assistance',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:36.587Z',
      fModificado: null,
      fborrado: null,
      id: 6,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Validation assistance',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:42.243Z',
      fModificado: null,
      fborrado: null,
      id: 7,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
    {
      UserBorrado: null,
      UserCreado: 51,
      UserModificado: null,
      borrado: false,
      descripcion: 'Customer request other work',
      descripcion_br: null,
      descripcion_de: null,
      descripcion_dk: null,
      descripcion_en: null,
      descripcion_fr: null,
      descripcion_it: null,
      descripcion_pt: null,
      descripcion_ru: null,
      descripcion_us: null,
      extId: '',
      fCreado: '2019-05-17T12:08:46.26Z',
      fModificado: null,
      fborrado: null,
      id: 8,
      idParent: 0,
      intOrder: 0,
      strIdEnvironment: ';-1;',
    },
  ],
};

export default lists;
